DROP DATABASE IF EXISTS bank_db;
CREATE DATABASE bank_db;

DROP USER IF EXISTS admin;
CREATE USER 'admin' IDENTIFIED BY 'Admin.123';
GRANT ALL PRIVILEGES ON bank_db.* TO 'admin';


DROP TABLE IF EXISTS bank_db.todos;
CREATE TABLE bank_db.todos (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;