version: '3'

networks:
  myapp-go:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: app
    ports:
      - 9000:9000
    volumes:
      - ./src:/golang-docker
      - .env:/golang-docker/.env
    depends_on:
      - redis
      - mysql
    networks:
      - myapp-go

  go:
    image: golang:alpine
    container_name: go
    volumes:
      - ./src:/golang-docker
      - .env:/golang-docker/.env
    working_dir: /golang-docker
    profiles: ["go"]
    entrypoint: ['go']
    networks:
      - myapp-go

  mysql:
    image: mariadb:10.6
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    # volumes:
    #   - ./mysql:/var/lib/mysql
    networks:
      - myapp-go
    
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6380:6379
    networks:
      - myapp-go

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: ${DB_PORT}
    depends_on:
      - mysql
    ports:
      - 8888:80
    networks:
      - myapp-go